kind: Deployment
apiVersion: apps/v1
metadata: 
  name: mydep
spec:
  replicas: 2
  selector: 
    matchLabels:
      name: deployment
  template:
    metadata:
      name: testpod
      labels:
        name: deployment
    spec:
      containers:
        - name: c02
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo second deployment; sleep 20; done"]
